title: Grace Pasion
email: grpasion@outlook.com
description: "Machine learning student & builder — projects, blog, resume."
baseurl: "" # leave empty for user site (not project site)
url: "https://your-username.github.io"

theme: minima

# site navigation (used by some themes or your layouts)
nav:
  - name: "Home"
    link: "/"
  - name: "About"
    link: "/about/"
  - name: "Projects"
    link: "/projects/"
  - name: "Blog"
    link: "/blog/"

# Collections
collections:
  projects:
    output: true
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project

# other settings
permalink: /:title/
